# Generated by Django 2.0.5 on 2018-05-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NEWS_BROADCAST',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('title', models.TextField(max_length=100)),
                ('content', models.TextField()),
                ('uploadDate', models.CharField(max_length=10)),
                ('updateDate', models.DateTimeField()),
            ],
        ),
    ]
