# Generated by Django 2.0.5 on 2018-05-07 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0002_auto_20180507_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_document',
            name='updateDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
