# Generated by Django 2.0.5 on 2018-05-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0003_web_document_updatedate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WEB_DOCUMENT',
            new_name='NEWS_BROADCAST',
        ),
    ]
