# Generated by Django 2.0.5 on 2018-05-07 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0004_auto_20180507_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_broadcast',
            name='uploadDate',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
